// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"helloworld/internal/infrastructure/ent/author"
	"helloworld/internal/infrastructure/ent/book"
	"helloworld/internal/infrastructure/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGoogleBooksID sets the "google_books_id" field.
func (_u *BookUpdate) SetGoogleBooksID(v string) *BookUpdate {
	_u.mutation.SetGoogleBooksID(v)
	return _u
}

// SetNillableGoogleBooksID sets the "google_books_id" field if the given value is not nil.
func (_u *BookUpdate) SetNillableGoogleBooksID(v *string) *BookUpdate {
	if v != nil {
		_u.SetGoogleBooksID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdate) SetTitle(v string) *BookUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *BookUpdate) SetSubtitle(v string) *BookUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *BookUpdate) SetNillableSubtitle(v *string) *BookUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *BookUpdate) ClearSubtitle() *BookUpdate {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdate) SetUpdatedAt(v time.Time) *BookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAuthorIDs adds the "authors" edge to the Author entity by IDs.
func (_u *BookUpdate) AddAuthorIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddAuthorIDs(ids...)
	return _u
}

// AddAuthors adds the "authors" edges to the Author entity.
func (_u *BookUpdate) AddAuthors(v ...*Author) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuthorIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearAuthors clears all "authors" edges to the Author entity.
func (_u *BookUpdate) ClearAuthors() *BookUpdate {
	_u.mutation.ClearAuthors()
	return _u
}

// RemoveAuthorIDs removes the "authors" edge to Author entities by IDs.
func (_u *BookUpdate) RemoveAuthorIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveAuthorIDs(ids...)
	return _u
}

// RemoveAuthors removes "authors" edges to Author entities.
func (_u *BookUpdate) RemoveAuthors(v ...*Author) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuthorIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdate) check() error {
	if v, ok := _u.mutation.GoogleBooksID(); ok {
		if err := book.GoogleBooksIDValidator(v); err != nil {
			return &ValidationError{Name: "google_books_id", err: fmt.Errorf(`ent: validator failed for field "Book.google_books_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := book.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "Book.subtitle": %w`, err)}
		}
	}
	return nil
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoogleBooksID(); ok {
		_spec.SetField(book.FieldGoogleBooksID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(book.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(book.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.AuthorsTable,
			Columns: book.AuthorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuthorsIDs(); len(nodes) > 0 && !_u.mutation.AuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.AuthorsTable,
			Columns: book.AuthorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.AuthorsTable,
			Columns: book.AuthorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetGoogleBooksID sets the "google_books_id" field.
func (_u *BookUpdateOne) SetGoogleBooksID(v string) *BookUpdateOne {
	_u.mutation.SetGoogleBooksID(v)
	return _u
}

// SetNillableGoogleBooksID sets the "google_books_id" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableGoogleBooksID(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetGoogleBooksID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookUpdateOne) SetTitle(v string) *BookUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *BookUpdateOne) SetSubtitle(v string) *BookUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableSubtitle(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *BookUpdateOne) ClearSubtitle() *BookUpdateOne {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BookUpdateOne) SetUpdatedAt(v time.Time) *BookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddAuthorIDs adds the "authors" edge to the Author entity by IDs.
func (_u *BookUpdateOne) AddAuthorIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddAuthorIDs(ids...)
	return _u
}

// AddAuthors adds the "authors" edges to the Author entity.
func (_u *BookUpdateOne) AddAuthors(v ...*Author) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuthorIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearAuthors clears all "authors" edges to the Author entity.
func (_u *BookUpdateOne) ClearAuthors() *BookUpdateOne {
	_u.mutation.ClearAuthors()
	return _u
}

// RemoveAuthorIDs removes the "authors" edge to Author entities by IDs.
func (_u *BookUpdateOne) RemoveAuthorIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveAuthorIDs(ids...)
	return _u
}

// RemoveAuthors removes "authors" edges to Author entities.
func (_u *BookUpdateOne) RemoveAuthors(v ...*Author) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuthorIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BookUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := book.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BookUpdateOne) check() error {
	if v, ok := _u.mutation.GoogleBooksID(); ok {
		if err := book.GoogleBooksIDValidator(v); err != nil {
			return &ValidationError{Name: "google_books_id", err: fmt.Errorf(`ent: validator failed for field "Book.google_books_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := book.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Book.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := book.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "Book.subtitle": %w`, err)}
		}
	}
	return nil
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoogleBooksID(); ok {
		_spec.SetField(book.FieldGoogleBooksID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(book.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(book.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(book.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.AuthorsTable,
			Columns: book.AuthorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuthorsIDs(); len(nodes) > 0 && !_u.mutation.AuthorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.AuthorsTable,
			Columns: book.AuthorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   book.AuthorsTable,
			Columns: book.AuthorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
