// Code generated by ent, DO NOT EDIT.

package ent

import (
	"helloworld/internal/infrastructure/ent/book"
	"helloworld/internal/infrastructure/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescGoogleBooksID is the schema descriptor for google_books_id field.
	bookDescGoogleBooksID := bookFields[1].Descriptor()
	// book.GoogleBooksIDValidator is a validator for the "google_books_id" field. It is called by the builders before save.
	book.GoogleBooksIDValidator = bookDescGoogleBooksID.Validators[0].(func(string) error)
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[2].Descriptor()
	// book.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	book.TitleValidator = bookDescTitle.Validators[0].(func(string) error)
	// bookDescSubtitle is the schema descriptor for subtitle field.
	bookDescSubtitle := bookFields[3].Descriptor()
	// book.SubtitleValidator is a validator for the "subtitle" field. It is called by the builders before save.
	book.SubtitleValidator = bookDescSubtitle.Validators[0].(func(string) error)
	// bookDescCreatedAt is the schema descriptor for created_at field.
	bookDescCreatedAt := bookFields[5].Descriptor()
	// book.DefaultCreatedAt holds the default value on creation for the created_at field.
	book.DefaultCreatedAt = bookDescCreatedAt.Default.(func() time.Time)
	// bookDescUpdatedAt is the schema descriptor for updated_at field.
	bookDescUpdatedAt := bookFields[6].Descriptor()
	// book.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	book.DefaultUpdatedAt = bookDescUpdatedAt.Default.(func() time.Time)
	// book.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	book.UpdateDefaultUpdatedAt = bookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookDescID is the schema descriptor for id field.
	bookDescID := bookFields[0].Descriptor()
	// book.DefaultID holds the default value on creation for the id field.
	book.DefaultID = bookDescID.Default.(func() uuid.UUID)
}
